# Generated by Django 5.2.1 on 2025-05-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='kode_user',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
