# Generated by Django 5.2.1 on 2025-05-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_user_jenis_kelamin_user_kode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kode_user',
        ),
    ]
