# Generated by Django 5.2.1 on 2025-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0004_user_jenis_kelamin_user_kode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kode_user',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
