# Generated by Django 5.2.1 on 2025-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0005_alter_user_kode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(),
        ),
    ]
