# Generated by Django 5.2.1 on 2025-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0006_alter_peminjaman_tanggal_pinjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_dikembalikan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
