# Generated by Django 5.2.1 on 2025-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0008_alter_peminjaman_tanggal_dikembalikan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='kode_laporan',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
