# Generated by Django 5.2.1 on 2025-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0010_peminjaman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
