# Generated by Django 5.2.1 on 2025-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0011_peminjaman_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
