# Generated by Django 5.2.1 on 2025-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0012_remove_peminjaman_barcode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='denda',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='denda_dibayar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Persetujuan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dikembalikan', 'Dikembalikan')], default='menunggu', max_length=20),
        ),
    ]
