# Generated by Django 5.2.1 on 2025-06-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0013_peminjaman_denda_peminjaman_denda_dibayar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sudah_update_profil',
            field=models.BooleanField(default=False),
        ),
    ]
